driver:
  name: vagrant
  customize:
    memory: 512

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  - name: ubuntu-14.04
    driver_config:
      box: ubuntu-14.04
      box_url: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box

suites:
- name: default
  run_list:
  - recipe[bosh-jumpbox::default]
